### ISSUE TITLE
What is "my_mo" in "4_exploratorio_modelo.R"

### ISSUE THREAD

**Issue by gc759** [rnanclares/forest-fires#4]
Hi Raul,

In 4_exploratorio_modelo.R, line 89, there is an object "my_mo" which was not previously defined. Could you please explain a bit what it is?

```r
fires_pro <- predict(my_mo, incendios_Test, type="prob")
```

Thanks you.

**Comment by rnanclares** [comment]
Closed by https://github.com/rnanclares/forest-fires/commit/47da7fd2f436a9c8fa5a53d58cae00822f0b65be
